# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/200_viewpoints.ipynb.

# %% auto #0
__all__ = ['PhysicalMirror', 'ViewpointConfig', 'angular_spread', 'TriMirrorRig']

# %% ../../nbs/200_viewpoints.ipynb #170c5cb0
from dataclasses import dataclass

import numpy as np
from scipy.optimize import differential_evolution
from scipy.spatial.transform import Rotation

type Vec3 = tuple[float, float, float]

# %% ../../nbs/200_viewpoints.ipynb #2b274166
@dataclass(frozen=True)
class PhysicalMirror:
    center: Vec3
    normal: Vec3


@dataclass(frozen=True)
class ViewpointConfig:
    camera: Vec3
    viewpoints: tuple[Vec3, ...]
    mirrors: tuple[PhysicalMirror, ...]
    target: Vec3 = (0.0, 0.0, 0.0)

    @property
    def mirror_zoom(self) -> float:
        direct_dist = np.linalg.norm(np.array(self.camera) - np.array(self.target))
        mirror_dist = np.linalg.norm(
            np.array(self.viewpoints[1]) - np.array(self.target)
        )
        return mirror_dist / direct_dist

# %% ../../nbs/200_viewpoints.ipynb #63dfba61
def angular_spread(config: ViewpointConfig) -> dict[str, float]:
    pts = np.array(config.viewpoints)
    dirs = pts - np.array(config.target)
    dirs = dirs / np.linalg.norm(dirs, axis=1, keepdims=True)

    cosines = np.clip(dirs @ dirs.T, -1.0, 1.0)
    angles = np.degrees(np.arccos(cosines))

    pairwise = angles[np.triu_indices(len(dirs), k=1)]

    return {
        "min": float(pairwise.min()),
        "max": float(pairwise.max()),
        "mean": float(pairwise.mean()),
        "angles": pairwise.tolist(),
    }

# %% ../../nbs/200_viewpoints.ipynb #3a08823d
@dataclass(frozen=True)
class TriMirrorRig:
    camera_dist: float
    ring_radius: float
    ring_height: float
    tilt: Vec3 = (0.0, 0.0, 0.0)

    def with_tilt(self, tilt: Vec3) -> "TriMirrorRig":
        return TriMirrorRig(self.camera_dist, self.ring_radius, self.ring_height, tilt)

    def viewpoint_config(self, target: Vec3 = (0.0, 0.0, 0.0)) -> ViewpointConfig:
        cam = np.array([0.0, self.camera_dist, 0.0])
        centers = self._mirror_centers()

        rotvec = np.array(self.tilt)
        if np.linalg.norm(rotvec) > 1e-12:
            rot = Rotation.from_rotvec(rotvec)
            cam = rot.apply(cam)
            centers = [rot.apply(c) for c in centers]

        tgt = np.array(target)
        mirrors = []
        viewpoints = [tuple(cam.tolist())]
        for c in centers:
            d_cam = cam - c
            d_tgt = tgt - c
            n = d_cam / np.linalg.norm(d_cam) + d_tgt / np.linalg.norm(d_tgt)
            n = n / np.linalg.norm(n)
            virtual = cam - 2 * np.dot(cam - c, n) * n
            mirrors.append(
                PhysicalMirror(
                    center=tuple(c.tolist()),
                    normal=tuple(n.tolist()),
                )
            )
            viewpoints.append(tuple(virtual.tolist()))
        return ViewpointConfig(
            camera=viewpoints[0],
            viewpoints=tuple(viewpoints),
            mirrors=tuple(mirrors),
            target=target,
        )

    def _mirror_centers(self) -> list[np.ndarray]:
        return [
            np.array(
                [
                    self.ring_radius * np.cos(2 * np.pi * i / 3),
                    -self.ring_height,
                    self.ring_radius * np.sin(2 * np.pi * i / 3),
                ]
            )
            for i in range(3)
        ]

    @staticmethod
    def optimize(
        camera_dist: float = 380.0,
        r_bounds: tuple[float, float] = (20.0, 300.0),
        h_bounds: tuple[float, float] = (10.0, 200.0),
    ) -> "TriMirrorRig":
        def objective(params: np.ndarray) -> float:
            rig = TriMirrorRig(camera_dist, params[0], params[1])
            config = rig.viewpoint_config()
            spread = angular_spread(config)
            return -spread["min"]

        result = differential_evolution(
            objective,
            bounds=[r_bounds, h_bounds],
            seed=42,
            tol=1e-10,
            maxiter=5000,
        )
        return TriMirrorRig(camera_dist, result.x[0], result.x[1])
