# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_data.ipynb.

# %% auto #0
__all__ = ['DATA_DIR', 'PHOTOS_DIR', 'MIN_IMAGES_PER_CLASS', 'RANDOM_SEED', 'LegoDataset', 'load_class_map', 'load_image_paths']

# %% ../nbs/00_data.ipynb #a0a766db
from pathlib import Path
from PIL import Image
import numpy as np
from torch.utils.data import Dataset
from torchvision import transforms

# %% ../nbs/00_data.ipynb #3db811b7
DATA_DIR = Path("../data/gdansk")
PHOTOS_DIR = DATA_DIR / "photos"
MIN_IMAGES_PER_CLASS = 5
RANDOM_SEED = 42

# %% ../nbs/00_data.ipynb #6268d0ef
class LegoDataset(Dataset):
    """LEGO brick image dataset from directory structure.

    Each subdirectory under `root` is a class, named by part number.
    """

    def __init__(
        self,
        image_paths: list[str],
        labels: np.ndarray,
        transform: transforms.Compose | None = None,
    ):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img = Image.open(self.image_paths[idx]).convert("RGB")
        if self.transform:
            img = self.transform(img)
        return img, self.labels[idx]

# %% ../nbs/00_data.ipynb #f42945a9
def load_class_map(
    photos_dir: Path = PHOTOS_DIR, min_images: int = MIN_IMAGES_PER_CLASS
) -> tuple[list[str], dict[str, int]]:
    """Load class names and build name→index mapping.

    Skips classes with fewer than `min_images` images.
    Returns (class_names, class_to_idx).
    """
    class_names = []
    for cls_dir in sorted(photos_dir.iterdir()):
        if not cls_dir.is_dir():
            continue
        count = len(
            list(cls_dir.glob("*.jpg"))
            + list(cls_dir.glob("*.jpeg"))
            + list(cls_dir.glob("*.png"))
        )
        if count >= min_images:
            class_names.append(cls_dir.name)
    class_to_idx = {name: i for i, name in enumerate(class_names)}
    return class_names, class_to_idx

# %% ../nbs/00_data.ipynb #4c07ae8a
def load_image_paths(
    photos_dir: Path = PHOTOS_DIR, class_to_idx: dict[str, int] | None = None
) -> tuple[list[str], list[int]]:
    """Load all image paths and their integer labels.

    If class_to_idx is provided, only loads classes present in the mapping.
    """
    if class_to_idx is None:
        _, class_to_idx = load_class_map(photos_dir)

    image_paths = []
    labels = []
    for cls_name, cls_idx in class_to_idx.items():
        cls_dir = photos_dir / cls_name
        for ext in ("*.jpg", "*.jpeg", "*.png"):
            for img_path in cls_dir.glob(ext):
                image_paths.append(str(img_path))
                labels.append(cls_idx)
    return image_paths, labels
