# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/304_multiview_fusion.ipynb.

# %% auto #0
__all__ = ['FusionLayer', 'FourViewDataset']

# %% ../nbs/304_multiview_fusion.ipynb #0ab0e0ba
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from dataclasses import dataclass
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from collections import defaultdict

# %% ../nbs/304_multiview_fusion.ipynb #ae82a9aa
class FusionLayer(nn.Module):
    """Aggregate N view embeddings into one part embedding.

    Modes:
        mean — average across views, L2-normalize.
        max  — element-wise max across views, L2-normalize.
        attention — learned per-view scores, softmax, weighted sum, L2-normalize.
    """

    def __init__(self, embed_dim: int, mode: str = "mean"):
        super().__init__()
        self.mode = mode
        if mode == "attention":
            self.scorer = nn.Linear(embed_dim, 1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """x: (batch, n_views, embed_dim) → (batch, embed_dim)"""
        if self.mode == "mean":
            fused = x.mean(dim=1)
        elif self.mode == "max":
            fused = x.max(dim=1).values
        elif self.mode == "attention":
            scores = self.scorer(x).squeeze(-1)
            weights = F.softmax(scores, dim=1).unsqueeze(-1)
            fused = (x * weights).sum(dim=1)
        else:
            raise ValueError(f"Unknown fusion mode: {self.mode}")
        return F.normalize(fused, p=2, dim=1)

# %% ../nbs/304_multiview_fusion.ipynb #9c4bb3b1
class FourViewDataset(Dataset):
    """Groups projected embeddings into 4-view tuples by render instance."""

    def __init__(
        self,
        projected_emb: np.ndarray,
        labels: np.ndarray,
        view_idx: np.ndarray,
        ldraw_id: np.ndarray,
        render_idx: np.ndarray,
        n_views: int = 4,
    ):
        groups: dict[tuple[str, int], dict[int, int]] = defaultdict(dict)
        for i, (lid, rid, vid) in enumerate(zip(ldraw_id, render_idx, view_idx)):
            groups[(str(lid), int(rid))][int(vid)] = i

        self.items = []
        self.group_labels = []
        for (lid, rid), view_map in groups.items():
            if len(view_map) < n_views:
                continue
            indices = [view_map[v] for v in range(n_views)]
            self.items.append(indices)
            self.group_labels.append(labels[indices[0]])

        self.projected_emb = torch.from_numpy(projected_emb).float()
        self.labels_array = np.array(self.group_labels)

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        indices = self.items[idx]
        views = self.projected_emb[indices]
        label = self.group_labels[idx]
        return views, label
