# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/301_metric_learning.ipynb.

# %% auto #0
__all__ = ['ProjectionHead', 'SupConLoss', 'ViewAwareSupConLoss', 'ViewAwareEmbeddingDataset', 'ViewGroupedSampler']

# %% ../nbs/301_metric_learning.ipynb #01933286
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from pathlib import Path
from torch.utils.data import Dataset, DataLoader, Sampler
from collections import defaultdict

# %% ../nbs/301_metric_learning.ipynb #048fef66
class ProjectionHead(nn.Module):
    """MLP projection head: linear → BN → ReLU → linear → L2-normalize."""

    def __init__(self, input_dim: int, proj_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, input_dim),
            nn.BatchNorm1d(input_dim),
            nn.ReLU(inplace=True),
            nn.Linear(input_dim, proj_dim),
        )

    def forward(self, x):
        return F.normalize(self.net(x), p=2, dim=1)

# %% ../nbs/301_metric_learning.ipynb #b74f1ab1
class SupConLoss(nn.Module):
    """Supervised contrastive loss (Khosla et al., 2020)."""

    def __init__(self, temperature: float = 0.1):
        super().__init__()
        self.temperature = temperature

    def forward(self, embeddings: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
        device = embeddings.device
        n = embeddings.shape[0]

        sim = embeddings @ embeddings.T / self.temperature

        labels = labels.unsqueeze(1)
        pos_mask = (labels == labels.T).float().to(device)
        pos_mask.fill_diagonal_(0)

        logits_max = sim.max(dim=1, keepdim=True).values
        logits = sim - logits_max.detach()

        self_mask = torch.eye(n, device=device)
        logits = logits - self_mask * 1e9

        exp_logits = torch.exp(logits) * (1 - self_mask)
        log_prob = logits - torch.log(exp_logits.sum(dim=1, keepdim=True) + 1e-12)

        pos_count = pos_mask.sum(dim=1)
        mean_log_prob = (pos_mask * log_prob).sum(dim=1) / (pos_count + 1e-12)

        valid = pos_count > 0
        loss = -mean_log_prob[valid].mean()
        return loss

# %% ../nbs/301_metric_learning.ipynb #4b1614f9
class ViewAwareSupConLoss(nn.Module):
    """Supervised contrastive loss with view-aware pair selection.

    Positives: same part AND same viewpoint.
    Excluded: same part, different viewpoint (no gradient).
    Negatives: different part.
    """

    def __init__(self, temperature: float = 0.1):
        super().__init__()
        self.temperature = temperature

    def forward(
        self,
        embeddings: torch.Tensor,
        labels: torch.Tensor,
        view_idx: torch.Tensor,
    ) -> torch.Tensor:
        device = embeddings.device
        n = embeddings.shape[0]

        sim = embeddings @ embeddings.T / self.temperature

        same_part = (labels.unsqueeze(1) == labels.unsqueeze(0)).float()
        same_view = (view_idx.unsqueeze(1) == view_idx.unsqueeze(0)).float()

        pos_mask = same_part * same_view
        pos_mask.fill_diagonal_(0)

        exclude_mask = same_part * (1 - same_view)

        self_mask = torch.eye(n, device=device)
        valid_mask = (1 - self_mask - exclude_mask).clamp(min=0)

        logits_max = sim.max(dim=1, keepdim=True).values
        logits = sim - logits_max.detach()

        exp_logits = torch.exp(logits) * valid_mask
        log_prob = logits - torch.log(exp_logits.sum(dim=1, keepdim=True) + 1e-12)

        pos_count = pos_mask.sum(dim=1)
        mean_log_prob = (pos_mask * log_prob).sum(dim=1) / (pos_count + 1e-12)

        valid = pos_count > 0
        loss = -mean_log_prob[valid].mean()
        return loss

# %% ../nbs/301_metric_learning.ipynb #d7e35958
class ViewAwareEmbeddingDataset(Dataset):
    """Dataset wrapping embeddings with part labels and view indices."""

    def __init__(
        self,
        embeddings: np.ndarray,
        labels: np.ndarray,
        view_idx: np.ndarray,
    ):
        self.embeddings = torch.from_numpy(embeddings).float()
        self.labels = torch.from_numpy(labels).long()
        self.view_idx = torch.from_numpy(view_idx).long()

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.embeddings[idx], self.labels[idx], self.view_idx[idx]

# %% ../nbs/301_metric_learning.ipynb #24697ec9
class ViewGroupedSampler(Sampler):
    """Samples batches of (part, view) groups for view-aware SupCon."""

    def __init__(
        self,
        labels: np.ndarray,
        view_idx: np.ndarray,
        groups_per_batch: int = 64,
        samples_per_group: int = 4,
        num_batches: int | None = None,
        rng_seed: int = 42,
    ):
        self.groups_per_batch = groups_per_batch
        self.samples_per_group = samples_per_group
        self.rng = np.random.default_rng(rng_seed)

        self.group_indices: dict[tuple[int, int], list[int]] = defaultdict(list)
        for i, (lab, vid) in enumerate(zip(labels, view_idx)):
            self.group_indices[(int(lab), int(vid))].append(i)

        self.valid_groups = [
            k for k, v in self.group_indices.items()
            if len(v) >= samples_per_group
        ]

        n_samples = sum(len(v) for v in self.group_indices.values())
        self._num_batches = num_batches or (
            n_samples // (groups_per_batch * samples_per_group)
        )

    def __iter__(self):
        for _ in range(self._num_batches):
            chosen = self.rng.choice(
                len(self.valid_groups),
                size=min(self.groups_per_batch, len(self.valid_groups)),
                replace=False,
            )
            batch = []
            for g_idx in chosen:
                group_key = self.valid_groups[g_idx]
                members = self.group_indices[group_key]
                selected = self.rng.choice(
                    members, size=self.samples_per_group, replace=len(members) < self.samples_per_group
                )
                batch.extend(selected.tolist())
            yield batch

    def __len__(self):
        return self._num_batches
