# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/301_metric_learning.ipynb.

# %% auto #0
__all__ = ['ProjectionHead', 'SupConLoss', 'EmbeddingDataset']

# %% ../nbs/301_metric_learning.ipynb #322902df
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from pathlib import Path
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from collections import Counter

# %% ../nbs/301_metric_learning.ipynb #5c54b942
class ProjectionHead(nn.Module):
    """MLP projection head: linear → BN → ReLU → linear → L2-normalize."""

    def __init__(self, input_dim: int, proj_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, input_dim),
            nn.BatchNorm1d(input_dim),
            nn.ReLU(inplace=True),
            nn.Linear(input_dim, proj_dim),
        )

    def forward(self, x):
        return F.normalize(self.net(x), p=2, dim=1)

# %% ../nbs/301_metric_learning.ipynb #58b9ff20
class SupConLoss(nn.Module):
    """Supervised contrastive loss (Khosla et al., 2020).

    For each anchor, all samples with the same label in the batch
    are positives — the loss pulls them together and pushes apart
    all negatives.
    """

    def __init__(self, temperature: float = 0.1):
        super().__init__()
        self.temperature = temperature

    def forward(self, embeddings: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
        device = embeddings.device
        n = embeddings.shape[0]

        # Cosine similarity matrix (embeddings assumed L2-normalized)
        sim = embeddings @ embeddings.T / self.temperature

        # Mask: same-label pairs (excluding self)
        labels = labels.unsqueeze(1)
        pos_mask = (labels == labels.T).float().to(device)
        pos_mask.fill_diagonal_(0)

        # For numerical stability
        logits_max = sim.max(dim=1, keepdim=True).values
        logits = sim - logits_max.detach()

        # Exclude self-similarity
        self_mask = torch.eye(n, device=device)
        logits = logits - self_mask * 1e9

        # Log-softmax over all non-self entries
        exp_logits = torch.exp(logits) * (1 - self_mask)
        log_prob = logits - torch.log(exp_logits.sum(dim=1, keepdim=True) + 1e-12)

        # Mean log-prob over positive pairs
        pos_count = pos_mask.sum(dim=1)
        mean_log_prob = (pos_mask * log_prob).sum(dim=1) / (pos_count + 1e-12)

        # Only include anchors that have at least one positive
        valid = pos_count > 0
        loss = -mean_log_prob[valid].mean()
        return loss

# %% ../nbs/301_metric_learning.ipynb #64768003
class EmbeddingDataset(Dataset):
    """Dataset wrapping pre-extracted embeddings and labels."""

    def __init__(self, embeddings: np.ndarray, labels: np.ndarray):
        self.embeddings = torch.from_numpy(embeddings).float()
        self.labels = torch.from_numpy(labels).long()

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.embeddings[idx], self.labels[idx]
