# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/305_retrieval_eval.ipynb.

# %% auto #0
__all__ = ['knn_predict', 'knn_eval', 'build_reference_db']

# %% ../nbs/305_retrieval_eval.ipynb #d4944e24
import numpy as np
import torch
import torch.nn.functional as F
from pathlib import Path
from collections import defaultdict

# %% ../nbs/305_retrieval_eval.ipynb #2b405631
def knn_predict(
    ref_emb: np.ndarray,
    ref_labels: np.ndarray,
    query_emb: np.ndarray,
    k: int,
) -> np.ndarray:
    """Predict labels via k-NN majority vote on cosine similarity."""
    sims = query_emb @ ref_emb.T
    top_k_idx = np.argpartition(-sims, k, axis=1)[:, :k]
    preds = []
    for i in range(len(query_emb)):
        neighbor_labels = ref_labels[top_k_idx[i]]
        counts = np.bincount(neighbor_labels)
        preds.append(counts.argmax())
    return np.array(preds)


def knn_eval(
    ref_emb: np.ndarray,
    ref_labels: np.ndarray,
    query_emb: np.ndarray,
    query_labels: np.ndarray,
    k_values: list[int],
) -> dict[str, float]:
    """Compute top-1 accuracy at each k and top-5 retrieval accuracy."""
    results = {}
    sims = query_emb @ ref_emb.T
    for k in k_values:
        preds = knn_predict(ref_emb, ref_labels, query_emb, k)
        results[f"k={k} top-1"] = float((preds == query_labels).mean())
    top5_idx = np.argpartition(-sims, 5, axis=1)[:, :5]
    top5_correct = sum(
        1 for i in range(len(query_emb))
        if query_labels[i] in ref_labels[top5_idx[i]]
    )
    results["top-5 retrieval"] = top5_correct / len(query_emb)
    return results

# %% ../nbs/305_retrieval_eval.ipynb #a756d477
def build_reference_db(
    projected_emb: np.ndarray,
    labels: np.ndarray,
    view_idx: np.ndarray,
    ldraw_id: np.ndarray,
    render_idx: np.ndarray,
    fusion_layer: torch.nn.Module,
    n_views: int = 4,
    device: str = "cpu",
) -> tuple[np.ndarray, np.ndarray]:
    """Build a fused 4-view reference database.

    Groups embeddings by (ldraw_id, render_idx), fuses each complete
    group through the fusion layer, then averages across render_idx
    to produce one reference embedding per part.

    Returns (ref_emb, ref_labels) where ref_labels are integer class IDs.
    """
    groups: dict[tuple[str, int], dict[int, int]] = defaultdict(dict)
    for i, (lid, rid, vid) in enumerate(zip(ldraw_id, render_idx, view_idx)):
        groups[(str(lid), int(rid))][int(vid)] = i

    fusion_layer.eval()
    fused_by_part: dict[str, list[np.ndarray]] = defaultdict(list)

    with torch.no_grad():
        for (lid, rid), view_map in groups.items():
            if len(view_map) < n_views:
                continue
            indices = [view_map[v] for v in range(n_views)]
            views = torch.from_numpy(projected_emb[indices]).float().unsqueeze(0).to(device)
            fused = fusion_layer(views).cpu().numpy().squeeze(0)
            fused_by_part[lid].append(fused)

    ref_embs = []
    ref_lids = []
    label_map = {str(lid): int(labels[i]) for i, lid in enumerate(ldraw_id)}

    for lid, embs in fused_by_part.items():
        avg = np.mean(embs, axis=0)
        avg = avg / (np.linalg.norm(avg) + 1e-12)
        ref_embs.append(avg)
        ref_lids.append(label_map[lid])

    return np.array(ref_embs), np.array(ref_lids)
