# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/001_hdris.ipynb.

# %% auto #0
__all__ = ['POLYHAVEN_API', 'HDRI_DIR_DEFAULT', 'DEFAULT_HDRI_QUOTAS', 'fetch_hdri_list', 'download_hdri', 'HdriQuota',
           'ensure_hdris', 'ScoredHdri', 'score_hdri', 'build_hdri_pool']

# %% ../../nbs/001_hdris.ipynb #6be86ac6
import json
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import numpy as np

type Vec3 = tuple[float, float, float]

# %% ../../nbs/001_hdris.ipynb #e123c282
POLYHAVEN_API = "https://api.polyhaven.com"
HDRI_DIR_DEFAULT = Path("../data/hdri")


def _polyhaven_get(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": "klods-syn/0.1"})
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def fetch_hdri_list(category: str = "all") -> list[str]:
    url = f"{POLYHAVEN_API}/assets?t=hdris"
    if category != "all":
        url += f"&c={category}"
    return list(_polyhaven_get(url).keys())


def download_hdri(
    name: str, out_dir: Path = HDRI_DIR_DEFAULT, resolution: str = "1k"
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{name}_{resolution}.exr"
    if out_path.exists():
        return out_path
    files = _polyhaven_get(f"{POLYHAVEN_API}/files/{name}")
    exr_url = files["hdri"][resolution]["exr"]["url"]
    req = urllib.request.Request(exr_url, headers={"User-Agent": "klods-syn/0.1"})
    with urllib.request.urlopen(req) as resp:
        out_path.write_bytes(resp.read())
    return out_path

# %% ../../nbs/001_hdris.ipynb #f43c0e85
@dataclass(frozen=True)
class HdriQuota:
    category: str
    count: int


DEFAULT_HDRI_QUOTAS: tuple[HdriQuota, ...] = (
    HdriQuota("indoor", 20),
    HdriQuota("studio", 15),
    HdriQuota("night", 8),
    HdriQuota("urban", 8),
    HdriQuota("outdoor", 5),
    HdriQuota("skies", 3),
    HdriQuota("sunrise-sunset", 3),
)


def ensure_hdris(
    quotas: tuple[HdriQuota, ...] = DEFAULT_HDRI_QUOTAS,
    out_dir: Path = HDRI_DIR_DEFAULT,
    resolution: str = "1k",
) -> list[Path]:
    rng = np.random.default_rng(42)
    seen: set[str] = set()
    paths: list[Path] = []

    for quota in quotas:
        names = [n for n in fetch_hdri_list(quota.category) if n not in seen]
        selected = (
            rng.choice(names, size=min(quota.count, len(names)), replace=False)
            if names
            else []
        )
        for name in selected:
            seen.add(name)
            try:
                paths.append(download_hdri(name, out_dir, resolution))
            except Exception as e:
                print(f"Skipping {name}: {e}")

    return paths

# %% ../../nbs/001_hdris.ipynb #c6eaa7d2
import mitsuba as mi


@dataclass(frozen=True)
class ScoredHdri:
    path: Path
    luminance: float
    dynamic_range: float  # log ratio of 99th to 10th percentile


def score_hdri(path: Path) -> ScoredHdri:
    img = np.array(mi.Bitmap(str(path)))
    lum = img[:, :, :3] @ [0.2126, 0.7152, 0.0722]
    p10, p99 = np.percentile(lum, [10, 99])
    dr = float(np.log1p(p99) - np.log1p(p10))
    return ScoredHdri(path, float(np.mean(lum)), dr)


def build_hdri_pool(
    paths: list[Path], min_luminance: float = 0.1
) -> tuple[list[ScoredHdri], np.ndarray]:
    scored = [score_hdri(p) for p in paths]
    pool = [s for s in scored if s.luminance >= min_luminance]
    if not pool:
        return [], np.array([])
    drs = np.array([s.dynamic_range for s in pool])
    weights = 1.0 / (1.0 + drs)
    weights /= weights.sum()
    return pool, weights
